homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include configuration/customize.yaml
  customize_domain: !include configuration/customize_domain.yaml

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3

config:
map:
sun:
cloud:

# Auto discovery components
cast:

# Custom configurations for components
automation: !include_dir_merge_list component_configuration/automation
device_tracker: !include_dir_merge_list component_configuration/device_tracker
discovery: !include component_configuration/discovery.yaml
frontend: !include component_configuration/frontend/frontend.yaml
group: !include component_configuration/groups.yaml
history: !include component_configuration/history.yaml
hue: !include component_configuration/hue.yaml
input_boolean: !include component_configuration/input_boolean.yaml
light: !include_dir_merge_list component_configuration/light_groups
logger: !include component_configuration/logger.yaml
recorder: !include component_configuration/recorder.yaml
script: !include_dir_merge_named component_configuration/scripts
sensor: !include_dir_merge_list component_configuration/sensors
sonos: !include component_configuration/sonos.yaml
tts: !include_dir_merge_list component_configuration/tts
updater: !include component_configuration/updater.yaml
zone: !include component_configuration/zones.yaml
