homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include configuration/customize.yaml
  customize_domain: !include configuration/customize_domain.yaml

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3

logger:
  default: info

updater:
  reporting: false

sun:

map:

config:

frontend:
  javascript_version: latest

automation: !include_dir_merge_list component_configuration/automation
device_tracker: !include_dir_merge_list component_configuration/device_tracker
discovery: !include component_configuration/discovery.yaml
google_assistant: !include component_configuration/google_assistant.yaml
group: !include component_configuration/groups.yaml
history: !include component_configuration/history.yaml
hue: !include component_configuration/hue.yaml
input_boolean: !include component_configuration/input_boolean.yaml
light: !include_dir_merge_list component_configuration/light_groups
media_player: !include_dir_merge_list component_configuration/media_players
recorder: !include component_configuration/recorder.yaml
script: !include_dir_merge_named component_configuration/scripts
sensor: !include_dir_merge_list component_configuration/sensors
tts: !include_dir_merge_list component_configuration/tts
zone: !include component_configuration/zones.yaml
