#################################################################
## Home Assistant
#################################################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include includes/customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'

logger:
  default: debug
updater:
  reporting: false
sun:
# conversation:
discovery:
  ignore:
    - sonos
map:
tts:
  - platform: google
config:
history:

frontend:
  javascript_version: latest

# Web UI interface
http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3

#################################################################
## Components
#################################################################

hue:
  bridges:
    - host: !secret hue_bridge_host
      allow_hue_groups: false
      allow_unreachable: true

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_assistant_api_key

#################################################################
## Includes
#################################################################
automation: !include_dir_merge_list automation
device_tracker: !include_dir_merge_list includes/device_tracker
media_player: !include_dir_merge_list includes/media_players
input_boolean: !include includes/input_boolean.yaml
sensor: !include_dir_merge_list includes/sensors
group: !include includes/groups.yaml
light: !include_dir_merge_list includes/light_groups
script: !include_dir_merge_named includes/scripts
zone: !include includes/zones.yaml
