homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include includes/customize.yaml
  customize_domain: !include includes/customize_domain.yaml

logger:
  default: info

updater:
  reporting: false

sun:

map:

config:

frontend:
  javascript_version: latest

discovery:
  ignore:
    - sonos

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3

hue:
  bridges:
    - host: !secret hue_bridge_host
      allow_hue_groups: false
      allow_unreachable: true

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_assistant_api_key

automation: !include_dir_merge_list automation
device_tracker: !include_dir_merge_list includes/device_tracker
history: !include includes/history.yaml
media_player: !include_dir_merge_list includes/media_players
input_boolean: !include includes/input_boolean.yaml
sensor: !include_dir_merge_list includes/sensors
group: !include includes/groups.yaml
light: !include_dir_merge_list includes/light_groups
script: !include_dir_merge_named includes/scripts
zone: !include includes/zones.yaml
tts: !include_dir_merge_list includes/tts
