version: '3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - /volume1/docker/home-assistant:/config
    restart: always
    network_mode: host
