##########################################################
## Bedtime
##########################################################

- alias: Bedtime

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  action:
    - service: light.turn_off
      entity_id: group.interior_lights
    - service: media_player.media_stop
      entity_id:
        - media_player.gym

##########################################################
## Reset Bedtime Switch
##########################################################

- alias: Bedtime - Reset Switch

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.bedtime
